#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly ROOT

bash -n "$ROOT/install.sh"
bash -n "$ROOT/upgrade.sh"
bash -n "$ROOT/uninstall.sh"
bash -n "$ROOT/bin/plasmazones-mode-toggle"
bash -n "$ROOT/tests/live-stable-removal.sh"
bash -n "$ROOT/tests/live-screen-transfer.sh"
bash -n "$ROOT/tests/live-unified-movement.sh"
bash -n "$ROOT/tests/live-cross-screen-focus.sh"
bash -n "$ROOT/tests/live-pane-swap.sh"
bash -n "$ROOT/tests/live-workspace-transfer.sh"
jq empty "$ROOT/layouts/hybrid-grid-3x2.json"
jq empty "$ROOT/rules/stable-geometry.json"
jq empty "$ROOT/rules/float-steam.json"
node --check "$ROOT/tests/live-coverage.js"
node --check "$ROOT/tests/live-fancy-coverage.js"
node "$ROOT/tests/stable-removal.js"
jq empty "$ROOT/profile/omarchy-on-kde-profile.json"
grep -q '@EXEC@' "$ROOT/share/applications/plasmazones-mode-toggle.desktop.in"
grep -q 'tiling_algorithm="dwindle-memory"' "$ROOT/bin/plasmazones-mode-toggle"
grep -q 'PZH Grow Height' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'setWindowFloatingForScreen' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'isTilingCandidate' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'insertWindowAtFocusedLeaf' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'removeWindowPreservingShape' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'moveFocusedToScreen' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'moveFocusedAcrossLayout' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'insertWindowAtArrivalBoundary' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'buildCanonicalTree' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'PZH Direct Screen' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'directionalNeighbor(source, direction, "other")' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'touchesOutputEdge(source, direction)' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'pendingScreenTransfers' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'trackingRequested' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'beginPendingScreenTransfer' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'armPendingScreenTransfer' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q '"invokeShortcut", action' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'GLOBAL_ACCEL_OBJECT = "/component/plasmazonesd"' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'geometriesMatch' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'remove_active_output_rules' "$ROOT/bin/plasmazones-mode-toggle"
if grep -q 'upsert_active_output_rule' "$ROOT/install.sh"; then
    exit 1
fi
grep -q 'outputForContextKey' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'keepAbove = false' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'PZH Fancy Adaptive Reflow' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"
grep -q 'handleBatchedResnap' "$ROOT/kwin/plasmazones-omarchy-lock/contents/code/main.js"

echo "Smoke tests passed."
